name: Test deploy

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker-compose pull
        docker-compose build
        docker-compose config
        docker-compose up -d
        sleep 180
        docker-compose ps
        docker-compose logs
        docker-compose down -v
      
